export const t_investigation_rows = [
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (785, '收监法律文书是否齐全、无误', -1, 2)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (786, '收押罪犯是否符合规定条件、范围', -1, 2)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (788, '收监罪犯和法律文书是否相符', -1, 2)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (789, '收监罪犯是否进行人身检查', -1, 2)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (790, '收监罪犯是否进行携带物品检查', -1, 2)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (791, '罪犯收监后，是否5日内通知其家属', -1, 2)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (792, '监狱有关收监的其他执法活动', -1, 2)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (793, '出监法律文书是否齐全、无误，有关社区矫正和监外执行的法律文书是否送达', -1, 3)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (794, '出监罪犯和法律文书是否相符', -1, 3)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (795, '出监罪犯是否按期释放，是否进行人身、物品检查', -1, 3)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (796, '监狱有关出监的其他执法活动', -1, 3)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (797, '监狱提请减刑、假释的案件是否符合法律规定，程序是否合法，证据是否确实、充分', -1, 4)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (798, '应当开庭审理的减刑、假释案件是否开庭审理', -1, 4)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (799, '监狱是否依法派员参加庭审，宣读提请减刑、假释建议书并举证、质证，配合法庭核实证据等', -1, 4)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (800, '人民法院减刑、假释裁定是否符合法律规定，证据是否确实、充分', -1, 4)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (801, '人民法院审理、裁定减刑、假释案件的程序是否符合法律规定', -1, 4)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (802, '减刑、假释裁定书是否依法送达执行并向社会公布', -1, 4)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (803, '监狱、人民法院有关减刑、假释的其他执法活动', -1, 4)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (804, '监狱提请暂予监外执行的案件是否符合法律规定，程序是否合法，证据是否确实、充分', -1, 5)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (805, '省级监狱管理机关批准暂予监外执行的案件是否符合法律规定，程序是否合法，证据是否确实、充分', -1, 5)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (806, '监狱和省级监狱管理机关有关暂予监外执行的其他执法活动', -1, 5)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (807, '罪犯的控告、举报、申诉材料，监狱是否依法转交有关机关处理', -1, 6)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (808, '监狱依据罪犯申诉，认为判决可能有错误的，是否提请人民检察院或者人民法院处理', -1, 6)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (809, '监狱是否依法尊重和保障罪犯的控告、举报、申诉等合法权益', -1, 6)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (810, '监狱有关罪犯控告、举报、申诉的执法活动', -1, 6)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (811, '监狱安全警戒设施设备是否符合规定', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (812, '监狱门禁系统设施设置和管理是否符合规定', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (813, '监狱安全监管设施是否符合规定', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (814, '监狱禁闭室、会见室等场所是否符合建设标准', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (815, '监狱生产劳动场所安全是否符合规定', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (816, '监狱消防设施及火灾防范措施是否符合规定', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (817, '监狱对危险源、危险物品的管理和使用是否符合规定', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (818, '清监查号、违禁品搜查等监狱安全规章制度是否落实，应急预案制订和执行是否符合规定', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (819, '监狱有关监管安全的其他执法活动', -1, 8)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (820, '成年男犯、女犯和未成年犯是否实行分开关押和管理', -1, 9)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (821, '女犯是否由女性监狱民警直接管理', -1, 9)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (822, '罪犯是否按照犯罪类型、刑罚种类、刑期、改造表现等情况，对罪犯实行分别关押，采用不同管理方式', -1, 9)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (823, '老病残罪犯是否分别管理，在生活、劳动等各方面予以适当照顾', -1, 9)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (824, '罪犯是否根据考核积分、服刑时间、犯罪类型和主观恶性等情况，对罪犯实行分级管理，在活动范围、会见通信、文体活动、离监探亲等方面给予相应的处遇', -1, 9)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (825, '特殊岗位罪犯的审批、使用、管理是否符合有关规定', -1, 9)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (826, '监狱对罪犯使用戒具是否符合规定的情形，是否存在滥用戒具作为刑讯和惩罚罪犯的手段的情形', -1, 10)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (827, '监狱对罪犯使用戒具是否严格履行审批手续，是否存在随意延长戒具使用时间的情形', -1, 10)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (828, '监狱是否使用制式警戒具，对罪犯使用戒具是否严格按照使用说明正确使用，是否存在给罪犯戴双铐、背铐、双镣等情形', -1, 10)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (829, '监狱是否安排医生定时对使用戒具的罪犯进行身体检查，是否存在身体状况不适宜而继续使用戒具的情形', -1, 10)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (830, '监狱是否按照规定的时间、次数为罪犯安排会见', -1, 11)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (831, '会见人员是否确系罪犯亲属、监护人，是否办理相关手续', -1, 11)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (832, '会见和拨打电话现场是否由监狱民警全程监听、监控、监管', -1, 11)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (833, '罪犯与亲属、监护人通信是否得到保障，是否依法实施了检查', -1, 11)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (834, '罪犯写给监狱的上级机关和司法机关的信件是否不被检查', -1, 11)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (835, '罪犯个人款物、生活卫生物资和设施设备、配餐中心、罪犯超市的设置和管理是否符合规定', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (836, '监狱医技人员资质，对医疗设备和药品的采购、使用、发放情况是否符合规定', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (837, '罪犯健康档案的建立、巡诊制度开展、罪犯门诊、住院及转院是否符合规定', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (838, '罪犯传染病预防、控制管理是否符合规定', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (839, '艾滋病罪犯、精神病罪犯的管理是否符合规定', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (840, '监狱突发公共卫生事件的应急准备、应急响应等是否符合规定', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (841, '现场查看刀具（刃）的发放、使用、回收、报废、登记各环节管理和相关记录，是否由指定监狱民警专人负责', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (842, '定期检察炊事员选用、轮换、撤销是否符合规定，是否办理《健康证》、是否开展安全教育和技能培训', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (843, '抽查食品留样各环节、留样记录、监狱民警现场监督是否符合规定，是否按早、中、晚分别保存，保留48小时', -1, 12)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (844, '罪犯的奖惩、考核是否按照司法部《关于计分考核奖罚罪犯的规定》等有关规定执行', -1, 13)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (845, '监狱对罪犯的行政奖励和处罚是否事实清楚，证据充分、程序合法，是否符合应当奖励和处罚的情形', -1, 13)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (846, '罪犯的行政奖励措施是否为表扬、记功、物质奖励、离监探亲四种情形', -1, 13)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (847, '罪犯的行政处罚措施是否为警告、记过、禁闭3种情形', -1, 13)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (848, '罪犯的考核是否分为教育改造和劳动改造两个部分，两个部分考核所占分值是否正确。在监狱服刑期间是否连续考核', -1, 13)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (849, '罪犯的加扣分是否事实清楚、证据充分、记载完整，加扣分值、加扣分审批程序与限权是否符合规定。月考核得分是否在监区内公示', -1, 13)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (850, '罪犯适用禁闭的条件、程序，执行禁闭的期限、条件、生活等保障，监狱民警对罪犯的教育', -1, 13)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (851, '监狱评选的改造积极分子是否符合评选条件，程序是否符合规定', -1, 13)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (852, '罪犯脱逃', -1, 14)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (853, '突发公共卫生事件', -1, 14)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (854, '罪犯伤残', -1, 14)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (855, '罪犯非正常死亡', -1, 14)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (856, '其他事故', -1, 14)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (857, '监狱主要领导是否定期深入监狱一线检查督导工作，帮助监区研究解决监管安全和队伍建设工作中存在的突出问题', -1, 15)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (858, '是否严格实行刑罚执行、狱政管理等部门负责人定期轮岗交流制度', -1, 15)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (859, '监狱是否加强基层基础工作，保证75%以上的警力配置在监区（分监区）', -1, 15)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (860, '监狱是否建立警务督察制度和督察机构，成立由专门人员组织的警务督察队，定期或不定期开展警务督察活动', -1, 15)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (861, '入监教育是否在新收分流罪犯的监狱或者监区集中进行', -1, 18)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (862, '入监教育时限是否符合省级监狱管理机关的规定', -1, 18)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (863, '监狱是否告知罪犯刑罚执行期间权利、义务', -1, 18)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (864, '入监教育是否包含法制教育、法律常识教育、认罪悔罪教育、监规纪律教育、行为规范教育等', -1, 18)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (865, '监狱对入监罪犯是否建立服刑改造专档', -1, 18)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (866, '监狱是否了解和掌握新收罪犯基本情况、认罪态度和思想动态，进行个体分析和心理测试，对其危险程度、恶性程度、改造难度进行评估，提出关押和改造建议', -1, 18)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (867, '监狱是否对入监教育结束后的罪犯进行考核验收，对考核合格的是否及时移送对应类别的监区服刑改造，对考核不合格的是否按规定延长入监教育', -1, 18)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (868, '监狱有关入监教育的其他执法活动', -1, 18)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (869, '检察出监教育是否集中进行', -1, 19)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (870, '检察出监教育时限是否为3个月，对未成年犯的出所教育是否不少于2个月', -1, 19)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (871, '出监教育内容是否包含形势、政策、前途教育，遵纪守法教育，必要的就业指导，必要的职业技术培训；对未成年犯出所教育还应包含形势、政策、遵纪守法等方面，是否在就业、复学等方面指导，提供必要的技能培训', -1, 19)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (872, '是否邀请当地公安、劳动和社会保障、民政、工商、税务等部门，向罪犯介绍有关治安、就业、安置、社会保障等方面的政策和情况，教育罪犯做好出监后应对各方面问题的思想准备', -1, 19)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (873, '是否根据罪犯在服刑期间的考核情况、奖惩情况、心理测验情况，对其改造效果进行综合评估', -1, 19)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (874, '是否在罪犯刑满前1个月，将其在监狱服刑改造的评估意见、刑满释放的时间，本人职业技能特长和回归社会后的择业意向，以及对地方做好安置帮教工作的建议，填入《刑满释放人员通知书》，寄送罪犯原户籍所在地的县级公安机关和司法行政机关', -1, 19)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (875, '监狱是否对刑满释放人员回归社会后的情况进行了解，评估教育改造工作的质量和效果', -1, 19)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (876, '监狱有关出监教育的其他执法活动', -1, 19)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (877, '是否对罪犯进行法制、道德、形势、政策、前途等方面的思想教育改造工作', -1, 21)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (878, '是否使用由司法部监狱管理局统一编写的教材', -1, 21)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (879, '每年对成年罪犯的思想、文化、技术教学时间是否不少于500课时，每年对未成年犯是否不少于1000课时', -1, 21)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (880, '监狱对罪犯进行的思想教育内容是否包括：认罪悔罪教育、法律常识教育、公民道德教育、时事政治教育', -1, 21)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (881, '未成年犯的思想教育内容是否包括法律常识、所规纪律、形势政策、道德修养、人生观、爱国主义等', -1, 21)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (882, '未成年犯管教所是否配备符合国家规定学历的监狱民警担任教师，是否按押犯数4%的比例配备，是否使用罪犯担任教师', -1, 21)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (883, '监狱有关思想教育的其他执法活动', -1, 21)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (884, '监狱民警对所管理的罪犯每个月是否至少安排一次个别谈话教育', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (885, '监狱民警在下列情形出现时是否及时进行个别谈话教育：新入监或者服刑监狱、监区变更时；处遇变更或者劳动岗位调换时；受到奖励或者惩处时；罪犯之间产生矛盾或者发生冲突时；离监探亲前后或者家庭出现变故时；无人会见或者家人长时间不与其联络时；行为反常、情绪异常时；主动要求谈话时；暂予监外执行、假释或刑满释放出监前', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (886, '监狱民警开展个别谈话教育是否做好记录', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (887, '监狱是否建立罪犯思想动态分析制度，是否按照监区每半月分析1次、监狱每月分析1次的要求开展罪犯思想动态分析', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (888, '监狱是否开展有针对性的专题教育', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (889, '监狱是否开展分类教育', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (890, '监狱是否建立顽固犯和危险犯的认定和教育转化制度', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (891, '监狱是否建立顽固犯和危险犯教育转化档案、由专人负责转化工作', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (892, '顽固犯和危险犯的认定与撤销程序是否符合规定', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (893, '是否根据未成年犯的案情、刑期、心理特点和改造表现进行有针对性的个别教育，实行教育转化责任制', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (894, '监狱有关个别教育的其他执法活动', -1, 22)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (895, '监狱是否与罪犯原所在地政府、单位（学校）、亲属联系或社会有关部门签订帮教协议', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (896, '监狱是否充分利用社会力量，建立一支相对稳定的帮教志愿者队伍，为社会志愿者参与帮教活动提供便利', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (897, '监狱是否适时邀请有关单位和人士来监狱开展帮教工作', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (898, '监狱是否联系、协调当地法律援助机构为需要的罪犯提供法律援助服务', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (899, '监狱开展社会帮教的审批手续是否符合规定', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (900, '监狱开展社会帮教活动是否组织有序、符合监狱安全管理规定', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (901, '监狱开展的社会帮教是否有益于罪犯改造', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (902, '对未成年人的社会教育，是否采取到社会上参观或者参加公益活动，邀请社会各界人士及未成年犯的父母或者其他监护人来所帮教的方法', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (903, '监狱有关社会帮教的其他执法活动', -1, 23)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (904, '监狱是否建立心理矫治室，配备必要设备', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (905, '是否由专人对罪犯进行心理矫治', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (906, '是否对罪犯进行心理健康教育，宣传心理健康知识', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (907, '是否在入监教育、服刑改造中期、出监教育期间对罪犯进行心理测验、评估，建立心理档案', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (908, '是否配备专门人员，对罪犯提供心理咨询服务', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (909, '对有心理疾病的罪犯是否实施治疗，对病情严重的是否组织有关专业人员会诊、进行专门治疗', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (910, '检察从事心理测验、心理咨询的工作人员是否具备相关资格，符合相关条件', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (911, '未成年犯管教所是否建立心理矫治机构，对未成年犯进行生理、心理健康教育，进行心理测试、心理咨询和心理矫治', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (912, '监狱有关心理矫治的其他执法活动', -1, 24)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (913, '监狱是否设立教育改造场所，包括教室、谈话室、文体活动室、图书室、阅览室、电化教育室、心理咨询室等，并配备相应的设施', -1, 26)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (914, '监狱是否根据罪犯不同文化程度分类进行扫盲、小学、初中文化教育或其他文化教育', -1, 26)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (915, '应当接受义务教育的罪犯是否依法接受教育', -1, 26)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (916, '接受文化教育考核合格后是否联系相关部门发放学业证书', -1, 26)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (917, '监狱开展扫盲、小学、初中文化教育是否使用司法部监狱管理局统一编写的教材', -1, 26)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (918, '对未成年犯的文化教育是否采取分年级编班施教，按规定的课程开课，使用经国务院教育行政部门审定的教材', -1, 26)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (919, '监狱有关文化教育的其他执法活动', -1, 26)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (920, '是否根据情况，成立文艺表演队、体育运动队等，组织罪犯开展适当的体育活动、文化娱乐和文艺活动', -1, 27)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (921, '是否办好图书室、阅览室、墙报、黑板报，组织开展经常性的读书、评报活动，监狱图书室藏书是否人均不少于10本', -1, 27)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (922, '是否根据条件，组织罪犯学习音乐、美术、书法等，开展艺术和美育教育', -1, 27)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (923, '是否建立电化教育系统、广播室，各监区是否配备电视，组织罪犯收听、收看新闻及其他有益于罪犯改造的广播、影视节目', -1, 27)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (924, '是否根据教育改造罪犯的需要，美化监区环境，规范监区环境布置，规范监狱文化标语设置', -1, 27)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (925, '是否在国庆节、国际劳动节、元旦、春节和重大庆祝、纪念活动，以及每月的第一天，组织罪犯参加升挂国旗仪式', -1, 27)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (926, '未成年犯管教所是否开展文化、娱乐、体育活动，办好报刊、黑板报、广播站、闭路电视，定期举行升国旗仪式，开展成人宣誓活动，根据需要，设立适合未成年犯特点的习艺劳动场所及其设施', -1, 27)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (927, '监狱有关监区文化建设的其他执法活动', -1, 27)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (928, '监狱对罪犯组织入监培训、岗前培训、在岗培训、转岗培训、安全生产培训是否符合国家相关规定', -1, 29)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (929, '监狱是否根据罪犯在狱内劳动的岗位技能要求和刑满释放后就业的需要，设置不同的岗位技术培训和职业技能教育内容，组织罪犯开展岗位技术培训和职业技能教育', -1, 29)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (930, '监狱是否对于未满50岁的且没有一技之长的罪犯，开展职业技术教育', -1, 29)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (931, '监狱是否积极与当地教育、劳动和社会保障行政部门以及就业培训机构联系，在技术教育的专业设置、教育安排、师资培训、外聘教师、教研活动、考试（考核）和颁发学历、学位（资格）证书方面获得支持和帮助', -1, 29)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (932, '监狱是否积极利用社会资源，开展技术教育，根据刑满释放后的就业需要，开设不同内容、种类的培训班', -1, 29)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (933, '监狱是否存在用劳动生产替代劳动技能教育培训的情形', -1, 29)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (934, '监狱对未成年犯的技术教育是否根据其刑期、文化程度和刑满释放后的就业需要，重点进行职业技术教育和技能培训', -1, 29)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (935, '监狱有关劳动技术教育的其他执法活动', -1, 29)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (936, '监狱引进或调整生产项目是否遵守国家有关法律法规，是否符合国家产业政策', -1, 30)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (937, '监狱是否存在组织罪犯从事易燃、易爆等高危行业生产、加工；是否存在组织罪犯从事有毒、有害等危险品生产、加工；是否存在组织罪犯从事假、冒、伪、劣产品的生产、加工；是否组织罪犯从事经营性食品、饮料的生产、加工；是否使用国家明令淘汰和禁止使用的设备、工艺', -1, 30)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (938, '检察监狱是否存在组织罪犯从事狱外劳动等违反规定的劳动项目', -1, 30)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (939, '监狱有关劳动生产项目的其他活动', -1, 30)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (940, '监狱是否组织罪犯在规定的区域和指定的劳动岗位劳动，并设置相应标志', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (941, '是否存在罪犯脱离监狱民警管理单独劳动的情形', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (942, '监狱落实劳动现场监狱民警直接管理制度，劳动现场的带班、值班监狱民警是否低于罪犯数的3%', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (943, '罪犯使用劳动工具是否符合相关制度', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (944, '罪犯使用劳动工具时现场是否有带班监狱民警进行监督管理', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (945, '除特殊工序外的锋利、尖角等易造成人员伤害的劳动工具是否进行钝化或者替代处理', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (946, '监狱劳动工具是否实行定人、定位、编号管理，刀具、刃具、钝器等有危险性的劳动工具是否上链管理；是否存在由罪犯保管、登记、分发有危险性的劳动工具的情况', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (947, '监狱对看板、标识牌、警示语、标语牌、信号灯等管理工具的使用及管理是否符合国家法律法规和相关部门的规定', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (948, '监狱对劳务加工外协人员的审核、监督及管理是否符合相关规定', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (949, '监狱在劳动现场的其他执法活动', -1, 31)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (950, '监狱是否制定安全教育培训计划，建立监狱民警、职工和作业人员的安全生产教育培训档案', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (951, '监狱安全生产管理机构负责人，是否经过安全生产培训合格；监狱民警、职工、罪犯是否存在未经安全生产培训合格，上岗作业的情形', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (952, '监狱对生产作业现场是否进行安全检查，对存在危险的劳动场所，是否设立安全警示标志、划定警戒区域', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (953, '监狱对危险作业场所、关键要害部位、重要时段的安全生产的监督管理措施是否完善', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (954, '监狱对隐患整治是否建立跟踪制度，是否定期举行安全生产隐患排查治理', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (955, '监狱对特种作业人员是否组织安全技术培训', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (956, '监狱对特种作业场所是否设立相关警示标志，划定警戒区域', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (957, '监狱对危险化学品的管理是否符合相关规定', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (958, '监狱新建、扩建、改建工程项目是否按照国家有关法律法规，落实消防安全管理措施', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (959, '监狱对易燃易爆危险物品的管理是否符合相关规定', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (960, '监狱对消防设施的安装、使用、维护是否符合国家有关法律法规的规定', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (961, '监狱在人员密集场所是否按规定设置符合紧急疏散要求的消防通道和安全出口，是否配备相应的消防设施器材和报警装置，消防设施器材和报警装置等是否注明使用办法', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (962, '监狱是否制定完善安全检查制度，明确部门、岗位的安全生产职责', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (963, '监狱是否对罪犯劳动现场实行定置管理。是否将物品仓库或休息场所设置在劳动现场；是否组织罪犯违规劳动；是否有罪犯将个人物品存放在劳动生产现场的情形；是否安排罪犯在锅炉房、配电房等关键要害岗位劳动', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (964, '监狱有关劳动安全的其他执法活动', -1, 32)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (965, '监狱企业是否执行国家有关劳动保护的规定，是否按照社会同行业、同工种的劳动保护要求，为参加劳动的罪犯按标准配备必须的劳动防护用品', -1, 33)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (966, '对有粉尘、噪声、辐射等污染的劳动场所，监狱是否按照规定安装通风、排气、除尘、降噪、防辐射等防护设施', -1, 33)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (967, '监狱对罪犯防寒保暖及防暑降温工作是否符合有关规定', -1, 33)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (968, '监狱对罪犯职业病的防范工作是否符合有关规定', -1, 33)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (969, '监狱在生产劳动中发生的罪犯致伤、致残或死亡事故，是否按照司法部有关规定进行补偿', -1, 33)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (970, '监狱有关劳动保障的其他执法活动', -1, 33)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (971, '监狱是否严格执行罪犯每周劳动5天，每天劳动时间不超过8小时，每周劳动时间不得超过40小时；未成年犯每天劳动4小时', -1, 34)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (972, '监狱是否严格执行监狱生产单位经批准后安排罪犯加班，每次不得超过3小时，每周平均不得超过6小时，连续加班不得超过3天的规定', -1, 34)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (973, '监狱是否存在法定节假日安排罪犯劳动的情形', -1, 34)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (974, '调整罪犯劳动时间是否经过监狱长的批准', -1, 34)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (975, '监狱对罪犯的劳动定额管理是否符合其生理特点，科学合理的确定', -1, 34)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (976, '监狱有关劳动工时的其他执法活动', -1, 34)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (977, '监狱是否严格落实罪犯劳动教育改造计分考核、行政奖惩相关制度，考核结果是否在各监区（分监区）统一公布', -1, 35)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (978, '监狱是否存在罪犯代为安排劳动项目、考核劳动改造计分等情形', -1, 35)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (979, '监狱是否明确规定罪犯劳动报酬的提取、管理、分配标准和使用办法，定期为参加劳动的罪犯发放劳动报酬', -1, 35)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (980, '监狱对未参加劳动的罪犯基本生活费的计发是否符合有关规定', -1, 35)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (981, '监狱是否对加班劳动的罪犯安排补休，确实不能补休的，是否给予补助', -1, 35)`,
`INSERT INTO t_investigation (id, title, value, typeId) VALUES (982, '监狱有关劳动绩效、劳动报酬的其他执法活动', -1, 35)`,
]

export const t_investigation_type_rows = [
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (1, '刑罚执行检察', 0, 0)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (2, '收监检察', 1, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (3, '出监检察', 1, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (4, '减刑、假释检察', 1, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (5, '暂予监外执行检察', 1, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (6, '控告、举报、申诉检察', 1, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (7, '狱政管理检察', 0, 0)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (8, '监管安全检察', 7, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (9, '分押分管检察', 7, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (10, '戒具使用检察', 7, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (11, '通信会见检察', 7, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (12, '生活卫生检察', 7, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (13, '罪犯奖惩、考核检察', 7, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (14, '事故检察', 7, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (15, '其他狱政管理检察', 7, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (16, '教育改造检察', 0, 0)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (17, '入监、出监教育检察', 16, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (18, '入监教育检察', 17, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (19, '出监教育检察', 17, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (20, '思想教育改造检察', 16, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (21, '思想教育检察', 20, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (22, '个别教育检察', 20, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (23, '社会帮教检察', 20, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (24, '心理矫治检察', 20, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (25, '文化教育改造检察', 16, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (26, '文化教育检察', 25, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (27, '监区文化建设检察', 25, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (28, '劳动教育改造检察', 16, 1)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (29, '劳动技术教育检察', 28, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (30, '劳动生产项目检察', 28, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (31, '劳动现场检察', 28, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (32, '劳动安全检察', 28, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (33, '劳动保障检察', 28, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (34, '劳动工时检察', 28, 2)`,
`INSERT INTO t_investigation_type (id, title, parentId, deep) VALUES (35, '劳动绩效、劳动报酬检察', 28, 2)`
]

const d1 = `'1、2018年第一季度提请减刑过程中，对28名涉毒服刑人员顶格呈报减刑，经法院裁定，均在7个月以下减刑；2考虑犯罪性质时，只掌握“8+1”犯罪从严，而对有组织的暴力性犯罪不审查，特别是在当前的“扫黑除恶”专项行动中，对恶势力的界定不认真研究，从而不能全面掌握从严情节；3有的监区民警对“稳定”的认识存在偏差。拿减刑幅度作为“稳定”的筹码；4是对法院的裁定不研究、不分析、不借鉴，在其后的呈报减刑中，继续顶格呈报。'`
const f1 = `'（1）针对在呈报减刑时强调现实行为表现，而对犯罪行为的性质、社会危害性考虑少，在呈报涉毒减刑案件中，不考虑毒品的危害程度、不学习对毒品案件应当从严掌握减刑的相关规定，对涉毒人员顶格呈报减刑的问题，监狱在办理2019年第二批减刑案件中已重点从犯罪行为的性质、社会危害性来从严把控减刑幅度，从1个表扬呈报减刑3个月从严到1个表扬至多呈报2个月来把控减刑幅度；对涉毒类罪犯呈报减刑时从严掌握。（2）针对提出的考虑犯罪性质时，只掌握“8+1”犯罪从严，而对有组织的暴力性犯罪不审查，特别是当前的“扫黑除恶”专项行动中，对恶势力的界定不认真研究，从而不能全面掌握从严情节的问题，监狱将组织办案民警学习，提高政治站位，牢牢把握刑罚执行工作的政治方向，坚决维护和严格执行党中央关于刑罚执行工作的指导意见和要求。对于涉黑涉恶人员严格从严把控，确保刑罚执行工作的政治方向。（3）针对有的监区民警对“稳定”的认识存在偏差，拿减刑幅度作为“稳定”的筹码的问题，监狱将进一步加强对民警的业务培训，端正执法理念，依法严格呈报减刑，正确发挥好减刑的激励功能。（4）关于对法院的裁定不研究、不分析、不借鉴的问题，监狱将组织办案民警认真分析讨论法院下达的裁定书，从中分析以后办案过程中需要注意的问题和事项。同时，监狱将加大办案民警的培训力度，提高执法能力，定期组织刑罚执行办案民警交流，对相关规定制度学懂、吃透，在实际执法实践中用准、用好，提高办案民警业务素质和办案能力。'`
const d2 = `'民警值班日志部分记录模糊，无法准确看出当天值班内容；监区民警值班日志不规范。一是值班日志格式不合理，填写主要工作的栏目留白太少，空格太小；二是记录的主要工作不全面，不能有效反映当日工作全貌。'`
export const t_history_problem_rows = [
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (1, 797, ${d1}, '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, ${f1})`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (2, 811, '监狱医院、三监区、四监区宿舍顶楼以及五监区车间顶楼的服刑人员通道没有安装防护栏或者限高安全护栏，存在安全隐患。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '关于医院、三监区、四监区宿舍顶层及五监区车间顶层罪犯通道没有限高防护栏的问题，监狱将结合省监狱局开展的安全警戒设施排查整治活动，列出清单，制定方案，一并整改，应当加装防护网限高护栏的部位都要加装。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (3, 813, '四监区和十一监区生产车间监控设施数量不足，没有做到全覆盖，车间四个角落属于监控死角区域；十监区监舍内监控数量不足、画质不清晰，晾晒场内两个监控探头视线基本被晾晒的衣服遮挡，出现监控死角，活动室仅有一个监控探头，无法监视整个活动室', '2019年武汉市城郊院对蔡甸监狱巡回检察', 0, '蔡甸监狱现被纳入湖北省监狱系统第一批智慧监狱建设“1252工程”。目前监狱已对第一中标施工单位进行了实地考察，签订施工合同，一年内完工。建成后，监狱共有约1700个探头，所有重点、关键部位将会实现高清晰、全覆盖数字化监控。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (4, 815, '监区内存在服刑人员触碰车间门或关门的情况，违反了服刑人员不得触碰门的监狱规定。如九监区存在服刑人员触碰车间门，五监区存在服刑人员开关车间门等情况；', '2019年武汉市城郊院对蔡甸监狱巡回检察', 0, null)`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (5, 816, '消防设施未通过验收投入使用，违反《消防法》等相关规定，监狱消防安全存在隐患。四监区消防疏散通道狭窄，无安全疏散标识，四监区、十一监区生产车间无消防栓、消防水带、喷淋系统。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 0, '监狱从2017年上半年就开始着手整改，拟对生产区域的消防管网进行升级改造，请专业消防公司设计施工方案，并报省局审核批准，施工方案已得到省局批复，230万的消防工程总投资目前正在项目招投标过程中。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (6, 816, '消防安全隐患仍存。监狱内物流中心存在安全隐患，在主要堆放布料等易燃物品区域内，无消防安全栓，顶部未安装消防水炮，顶部钢梁部分未涂刷防火漆。在伙房监区炒菜处未配备灭火毯。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 2, null)`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (7, 818, '清监力度不够，违规违禁物品大量存在，且物品摆放杂乱，管理力度不够。病房内存在输液针头、牙签、铁筷子和铁病历本等违规物品；发现监舍内存在大号指甲钳、铁片、短绳、木质筷子、皮带、用蚊帐自制的带子等违规物品', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '已纠正')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (8, 819, ${d2}, '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '关于民警值班日志填写不规范、记录内容少及值班日志格式不合理问题，监狱将结合对民警的业务培训工作，对值班日志记录制作填写模板，并作为日常检查考核的一项内容，督导监区认真规范记录值班日志，确保监区日志能全面真实反映日常工作。现在使用的值班日志是省局统一制作的，格式设计不合理问题，监狱将上报。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (9, 819, '监狱落实“一小时一点名”的规定不严，点名不规范。如九监区在点名时仅民警核对，服刑人员未答到。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 2, null)`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (10, 825, '蔡甸监狱现有监督岗中，原判死缓的有14人、原判无期徒刑16人、原判在15年以上的6人、累犯4人。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '已纠正')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (11, 825, '生产车间内的互监小组编排不合理，不能达到互监的目的。如在九监区生产车间检察时，发现九监区第八互监组内四名成员相隔较远，处于不同的工位，四名成员互相不在视线范围内；', '2019年武汉市城郊院对蔡甸监狱巡回检察', 2, null)`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (12, 836, '监狱医院管理严重违反相关法规。药房管理混乱，货架上摆放药品10种药品过期，未及时清理，存在用药安全隐患；服刑人员无职业资格证书，管理、使用药房电脑，操作药房电脑管理系统，从事发药等事务性工作；服刑人员保管药房药柜的钥匙；服刑人员从事打针、输液等护理工作；从事药房工作和护理工作的服刑人员，在囚服外穿着白大褂，着装不规范；药品管理不达标、不规范，需冷链保存的药品未按规定存放，已开具处方和未开具处方的药品混放在治疗室的冰箱内；管控药品未按规定制作明细台账；传染病区未达到隔离要求且消毒措施不到位，通风条件不好，并存在结核病犯与肝炎病犯混关情况；未开具抗结核类药品处方；急救室流于形式，大量过期药品随意堆放，且过期药品没有清单，未及时处理。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 0, '蔡甸监狱已迅速启动执业护士的招聘工作，正在从社会上招聘执业药剂师及有资质的男护士，专门从事打针、输液等护理工作，目前正在落实当中。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (13, 843, '服刑人员食堂管理不规范，存在食品安全隐患。罪犯食堂从业人员没有在蔡甸区疾控管理中心办理《健康证》；食堂送餐容器未消毒；食堂仓库内货架不足导致味精等部分食品调味料堆放在地上并未离地隔墙；面粉未隔墙存放；清洗好的肉类食品未离地存放；未见到食品进货索证；食品留样不符合标准，留样量不足125g的标准。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '已纠正')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (14, 844, '有的民警在计分考核中不认真负责，在换算行政奖励中出现了问题。如吴启发由无期徒刑减为有期徒刑案件中，反映出民警在计分考核时工作不认真负责，将3个嘉奖折算为1个记功。虽然监狱对此进行了更正，但也因此影响监狱整体呈报减刑工作，致吴启发的减刑呈报工作迟延。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '关于计分考核和行政奖励问题，监狱已发文进行过清查，清查发现的问题全都予以纠正。并重新发文确认（含罪犯吴启发的）。8月份，监狱将针对工作中发现的问题，依照计分考核工作相关规定再组织一次清查。后期发现因民警工作不认真不负责导致的计分考核和奖励错误问题，监狱将交纪检监察部门进行问责。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (15, 868, '教育内容不全面。在入监教育过程中，除了队列训练、背诵行为规范、唱红歌等内容外，关于政治教育的内容少，特别是开展升挂国旗活动，没有按照《司法部关于监狱教育改造工作规定》第38条的规定“每月的第一天，组织罪犯参加升挂国旗仪式”。同时，监狱没有根据罪犯的犯罪类型，结合罪犯的危险程度、恶性程度、接受能力、文化程度进行教育', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '关于入监教育中政治教育内容少、未根据罪犯的犯罪类型、文化程度等进行教育的问题的整改。监狱将进一步加强新投犯入监教育阶段的政治教育，在入监监区二楼悬挂入监誓词，每月组织新投犯集中宣誓。加大入监教育中的政治教育内容，同时，正在监内修建一个大型运动场，运动场上修建升旗台，待完工后每月的第一天，组织罪犯参加升国旗仪式。同时，监狱将根据罪犯的文化程度，分别开展扫盲教育、高自考教育和职业技能培训教育。创新政治教育途径，突出政治教育内容。健全政治教育制度。同时，监狱将根据罪犯的犯罪类型、危险程度、恶性程度，进行罪犯犯因与犯罪动机分析，开展因人施教、因策施教，进一步强化罪犯教育的针对性。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (16, 877, '民警对服刑人员的教育改造不够重视、管理松懈，不按时发放新一年度的笔记记录本；', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '已纠正')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (17, 877, '部分服刑人员学习笔记和改造周记记录简单、随意，甚至不标注日期或长达半年无学习记录；', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '已纠正')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (18, 877, '监区服刑人员的学习笔记和改造周记上无民警点评、批阅和签字，教育改造流于形式。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '已纠正')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (19, 883, '教育改造效果不强，监区存在违规杂志书籍。监狱未做好思想改造工作，改造效果不强。如蔡甸监狱刑满罪犯于华、龚家祥，在刑满后均再犯重大刑事案件，危害社会安全稳定，体现监狱对罪犯的教育改造效果不强；监区内大量存在违规的杂志书籍，未突出思想教育的重要性。如在十二监区清监中发现违规书籍《官仙4-当官是一门技术活》、《富豪俱乐部5-叱咤风云的女富豪》等书籍。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 2, null)`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (20, 886, '个别谈话教育流于形式。个别教育谈话内容没有以理服人、以情感人，没有戒之以规、导之以行，没有体现“教育”这个主题，个别教育不足百字，均为千篇一律的评价性结论，丧失“教育”的本义。有的民警对服刑人员的学习手册等没有进行查阅或批改签字，对服刑人员的教育措施没有落到实处。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '针对个别教育谈话内容未以理服人、以情感人，个别民警未对服刑人员手册进行查阅签字的问题。监狱在元月份民警“大培训、大比武、大练兵”中加强了对民警的教育培训，今后要特别加强民警教育管理罪犯的能力培训，提升民警个别教育工作能力和水平。同时，监狱教育科等业务科室每月对教育改造等业务工作进行一次检查考核，加强指导督促民警认真落实各项教育工作制度和要求。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (21, 895, '选择性进行社会帮教。监狱在开展社会帮教活动中，针对的范围不广泛，帮教活动只针对蔡甸籍的服刑人员，而对其他服刑人员则让其给当地司法行政部门写一封“特别家书”，没有与罪犯原所在地的政府、原单位（学校）或亲属签订帮教协议，有的只与服刑人员本人签订帮教协议，丧失“帮教”意义。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, '关于社会帮教活动中，针对范围不广泛，没有与罪犯原所在地政府、原单位（学校）及亲属签订帮教协议的整改。监狱正在打造“心桥回家”联合帮教品牌，建立常态化的监狱开放日制度，邀请罪犯亲属、人大代表及政协委员进监帮教。按照省监狱局的统一部署，监狱建立了“三联四知五包”工作制度，进一步加强与罪犯亲属和地方政府的联系。积极与社会帮教部门与罪犯家属签订帮教协议，努力把对罪犯的社会关爱帮教、家属亲情帮教效果发挥到最大实处。')`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (22, 946, '生产车间安全隐患多。四监区生产车间电烙、电插头等尖锐劳动维修工具随意摆放在生产车间角落的架子上，没有按照劳动工具的要求进行保管，存在安全隐患；十一监区生产车间有一根尖锐的铁丝（自制工具）链化，未进行编号管理，违反了劳动工具三定管理的要求，存在安全隐患，且箱子摆放过高，影响监控视野，存在安全隐患', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, null)`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (23, 971, '四监区、五监区和十一监区在执行劳动时间方面违反《监狱法》及省监狱管理局“5+1+1”制度的相关规定，多次未报请监狱机关审批，组织服刑人员在休息日进行劳动生产。', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, null)`,
`INSERT INTO t_history_problem (id, checkId, description, missionName, status, feedback) VALUES (24, 977, '计分考核制度落实不到位，截至2019年1月23日止，监狱对计分考核只公布到2018年8月份，计分考核工作滞后，违反了司法部《关于计分考核罪犯的规定》', '2019年武汉市城郊院对蔡甸监狱巡回检察', 1, null)`,
]

const c1 = `为认真贯彻党中央关于开展扫黑除恶专项斗争的重大决策部署，全面落实习近平总书记关于扫黑除恶与反腐败结合起来，与基层“拍蝇”结合起来的重要批示指示精神，进一步规范和加强各级监察机关、人民法院、人民检察院、公安机关、司法行政机关在惩治公职人员涉黑涉恶违法犯罪中的协作配合，推动扫黑除恶专项斗争取得更大成效，根据刑法、刑事诉讼法、监察法及最高人民法院、最高人民检察院、公安部、司法部《关于办理黑恶势力犯罪案件若干问题的指导意见》的规定，现就有关问题通知如下：
一、总体要求
1.进一步提升政治站位。坚持以习近平新时代中国特色社会主义思想为指导，从增强“四个意识”、坚定“四个自信”、做到“两个维护”的政治高度，立足党和国家工作大局，深刻认识和把握开展扫黑除恶专项斗争的重大意义。深挖黑恶势力滋生根源，铲除黑恶势力生存根基，严惩公职人员涉黑涉恶违法犯罪，除恶务尽，切实维护群众利益，进一步净化基层政治生态，推动扫黑除恶专项斗争不断向纵深发展，推进全面从严治党不断向基层延伸。
2.坚持实事求是。坚持以事实为依据，以法律为准绳，综合考虑行为人的主观故意、客观行为、具体情节和危害后果，以及相关黑恶势力的犯罪事实、犯罪性质、犯罪情节和对社会的危害程度，准确认定问题性质，做到不偏不倚、不枉不纵。坚持惩前毖后、治病救人方针，严格区分罪与非罪的界限，区别对待、宽严相济。
3.坚持问题导向。找准扫黑除恶与反腐“拍蝇”工作的结合点，聚焦涉黑涉恶问题突出、群众反映强烈的重点地区、行业和领域，紧盯农村和城乡结合部，紧盯建筑工程、交通运输、矿产资源、商贸集市、渔业捕捞、集资放贷等涉黑涉恶问题易发多发的行业和领域，紧盯村“两委”、乡镇基层站所及其工作人员，严肃查处公职人员涉黑涉恶违法犯罪行为。
二、严格查办公职人员涉黑涉恶违法犯罪案件
4.各级监察机关、人民法院、人民检察院、公安机关应聚焦黑恶势力违法犯罪案件及坐大成势的过程，严格查办公职人员涉黑涉恶违法犯罪案件。重点查办以下案件：公职人员直接组织、领导、参与黑恶势力违法犯罪活动的案件；公职人员包庇、纵容、支持黑恶势力犯罪及其他严重刑事犯罪的案件；公职人员收受贿赂、滥用职权，帮助黑恶势力人员获取公职或政治荣誉，侵占国家和集体资金、资源、资产，破坏公平竞争秩序，或为黑恶势力提供政策、项目、资金、金融信贷等支持帮助的案件；负有查禁监管职责的国家机关工作人员滥用职权、玩忽职守帮助犯罪分子逃避处罚的案件；司法工作人员徇私枉法、民事枉法裁判、执行判决裁定失职或滥用职权、私放在押人员以及徇私舞弊减刑、假释、暂予监外执行的案件；在扫黑除恶专项斗争中发生的公职人员滥用职权，徇私舞弊，包庇、阻碍查处黑恶势力犯罪的案件，以及泄露国家秘密、商业秘密、工作秘密，为犯罪分子通风报信的案件；公职人员利用职权打击报复办案人员的案件。
公职人员的范围，根据《中华人民共和国监察法》第十五条的规定认定。
5.以上情形，由有关机关依规依纪依法调查处置，涉嫌犯罪的，依法追究刑事责任。
三、准确适用法律
6.国家机关工作人员包庇黑社会性质的组织，或者纵容黑社会性质的组织进行违法犯罪活动的，以包庇、纵容黑社会性质组织罪定罪处罚。
国家机关工作人员既组织、领导、参加黑社会性质组织，又对该组织进行包庇、纵容的，应当以组织、领导、参加黑社会性质组织罪从重处罚。
国家机关工作人员包庇、纵容黑社会性质组织，该包庇、纵容行为同时还构成包庇罪、伪证罪、妨害作证罪、徇私枉法罪、滥用职权罪、帮助犯罪分子逃避处罚罪、徇私舞弊不移交刑事案件罪，以及徇私舞弊减刑、假释、暂予监外执行罪等其他犯罪的，应当择一重罪处罚。
7.非国家机关工作人员与国家机关工作人员共同包庇、纵容黑社会性质组织，且不属于该组织成员的，以包庇、纵容黑社会性质组织罪的共犯论处。非国家机关工作人员的行为同时还构成其他犯罪的，应当择一重罪处罚。
8.公职人员利用职权或职务便利实施包庇、纵容黑恶势力、伪证、妨害作证，帮助毁灭、伪造证据，以及窝藏、包庇等犯罪行为的，应酌情从重处罚。事先有通谋而实施支持帮助、包庇纵容等保护行为的，以具体犯罪的共犯论处。
四、形成打击公职人员涉黑涉恶违法犯罪的监督制约、配合衔接机制
9.监察机关、公安机关、人民检察院、人民法院在查处、办理公职人员涉黑涉恶违法犯罪案件过程中，应当分工负责，互相配合，互相制约，通过对办理的黑恶势力犯罪案件逐案筛查、循线深挖等方法，保证准确有效地执行法律，彻查公职人员涉黑涉恶违法犯罪。
10.监察机关、公安机关、人民检察院、人民法院要建立完善查处公职人员涉黑涉恶违法犯罪重大疑难案件研判分析、案件通报等工作机制，进一步加强监察机关、政法机关之间的配合，共同研究和解决案件查处、办理过程中遇到的疑难问题，相互及时通报案件进展情况，进一步增强工作整体性、协同性。
11.监察机关、公安机关、人民检察院、人民法院、司法行政机关要建立公职人员涉黑涉恶违法犯罪线索移送制度，对工作中收到、发现的不属于本单位管辖的公职人员涉黑涉恶违法犯罪线索，应当及时移送有管辖权的单位处置。
移送公职人员涉黑涉恶违法犯罪线索，按照以下规定执行：
（1）公安机关、人民检察院、人民法院、司法行政机关在工作中发现公职人员涉黑涉恶违法犯罪中的涉嫌贪污贿赂、失职渎职等职务违法和职务犯罪等应由监察机关管辖的问题线索，应当移送监察机关。
（2）监察机关在信访举报、监督检查、审查调查等工作中发现公职人员涉黑涉恶违法犯罪线索的，应当将其中涉嫌包庇、纵容黑社会性质组织犯罪等由公安机关管辖的案件线索移送公安机关处理。
（3）监察机关、公安机关、人民检察院、人民法院、司法行政机关在工作中发现司法工作人员涉嫌利用职权实施的侵犯公民权利、损害司法公正案件线索的，根据有关规定，经沟通后协商确定管辖机关。
12.监察机关、公安机关、人民检察院接到移送的公职人员涉黑涉恶违法犯罪线索，应当按各自职责及时处置、核查，依法依规作出处理，并做好沟通反馈工作；必要时，可以与相关线索或案件并案处理。
对于重大疑难复杂的公职人员涉黑涉恶违法犯罪案件，监察机关、公安机关、人民检察院可以同步立案、同步查处，根据案件办理需要，相互移送相关证据，加强沟通配合，做到协同推进。
13.公职人员涉黑涉恶违法犯罪案件中，既涉嫌贪污贿赂、失职渎职等严重职务违法或职务犯罪，又涉嫌公安机关、人民检察院管辖的违法犯罪的，一般应当以监察机关为主调查，公安机关、人民检察院予以协助。监察机关和公安机关、人民检察院分别立案调查（侦查）的，由监察机关协调调查和侦查工作。犯罪行为仅涉及公安机关、人民检察院管辖的，由有关机关依法按照管辖职能进行侦查。
14.公安机关、人民检察院、人民法院对公职人员涉黑涉恶违法犯罪移送审查起诉、提起公诉、作出裁判，必要时听取监察机关的意见。
15.公职人员涉黑涉恶违法犯罪案件开庭审理时，人民法院应当通知监察机关派员旁听，也可以通知涉罪公职人员所在单位、部门、行业以及案件涉及的单位、部门、行业等派员旁听。


                     2019年10月20日



`
export const t_law_rows = [
    `INSERT INTO t_law (id, name, title, content) VALUES (1, '《关于办理恶势力刑事案件若干问题的意见》', '最高人民法院 最高人民检察院 公安部 司法部\n《关于办理恶势力刑事案件若干问题的意见》', 3)`
]
